baseurl = "https://patrickod.github.io/eurorack.dev/"
disablePathToLower = true
languageCode = "en"
title = "eurorack dot dev"
subTitle = "a journey is musical making"
theme = "ezhil"
copyright = "Patrick O'Doherty"
relativeURLS = false

enableRobotsTXT = true
googleAnalytics = ""

[params]
  subtitle = "a journey in music making"
  mainSections = ["posts"]
 

[permalinks]
posts = "/:year/:month/:title"
