baseurl = "https://eurorack.dev"
disablePathToLower = true
languageCode = "en"
title = "eurorack dot dev"
subTitle = "a journey is musical making"
theme = "basics"
copyright = "Patrick O'Doherty"
relativeURLS = false

enableRobotsTXT = true
googleAnalytics = ""

[permalinks]
posts = "/:year/:month/:filename"
